Library/Library/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Library.AuthenticationService;
using Library.Common;
using Library.DB;
using Library.DTOs;
using Library.UserService.Domain.Models;
using System.Data.Entity.Migrations;
using Library.LogService.Domain.Models;
using Library.LogService.Domain;
using Library.LogService;

namespace Library.Controllers
{
    public class AdminController : Controller
    {
        private ApplicationDbContext context;
        private ILog _logger = Logger.GetInstance;

        public AdminController()
        {
            context = new ApplicationDbContext();
        }

        public ActionResult Index()
        {
            try
            {
                if (AuthenticationManager.LoggedUser != null && AuthenticationManager.IsAdmin() == true)
                {
                    List<User> users;
                    users = context.Users.ToList();
                    User admin = context.Users.SingleOrDefault(u => u.Id == AuthenticationManager.LoggedUser.Id);
                    users.Remove(admin);
                    return View(users);
                }
            }
            catch (Exception ex)
            {
                _logger.LogCustomExceptionAsync(ex, null);
            }

            return RedirectToAction("Error", "Home");
        }

        public ActionResult Edit(string id)
        {
            if (AuthenticationManager.LoggedUser != null && AuthenticationManager.IsAdmin() == true)
            {
                User user = context.Users.SingleOrDefault(u => u.Id == id);
                if (user == null)
                {
                    return RedirectToAction("Error", "Home");
                }
                UserEntry model = new UserEntry();
                model.Id = user.Id;
                model.IsAdmin = user.IsAdmin;

                return View(model);

            }

            return RedirectToAction("Error", "Home");
        }

        [HttpPost]
        public ActionResult Edit(UserEntry model)
        {
            if (AuthenticationManager.LoggedUser != null && AuthenticationManager.IsAdmin() == true)
            {
                User user = context.Users.SingleOrDefault(u => u.Id == model.Id);
                if (user == null)
                {
                    return RedirectToAction("Error", "Home");
                }
                user = UpdateUserAdminRights(user, model.IsAdmin);
                context.Users.AddOrUpdate(user);
                context.SaveChanges();


                return RedirectToAction("Index");
            }
            return RedirectToAction("Login", "Account");
        }

        public ActionResult Delete(string id)
        {
            if (AuthenticationManager.LoggedUser != null && AuthenticationManager.IsAdmin() == true)
            {
                User user = context.Users.SingleOrDefault(u => u.Id == id);
                if (user == null)
                {
                    return RedirectToAction("Error", "Home");
                }
                context.Users.Remove(user);
                context.SaveChanges();
                return RedirectToAction("Index");

            }
            return RedirectToAction("Error", "Home");
        }

        public ActionResult AllExceptions()
        {
            if (AuthenticationManager.LoggedUser != null && AuthenticationManager.IsAdmin() == true)
            {
                List<CustomException> exceptions = null;
                try
                {
                    exceptions = context.CustomExceptions
                        .OrderByDescending(e => e.DateCreated)
                        .Take(5)
                        .ToList();
                }
                catch (Exception ex)
                {
                    _logger.LogCustomExceptionAsync(ex, null);
                }
                return View(exceptions);
            }
            return RedirectToAction("Error", "Home");
        }

        private User UpdateUserAdminRights(User user, bool isAdmin)
        {
            var updatedUser = new User(
                user.Email,
                user.Password,
                user.ValidationCode,
                isAdmin,
                user.IsEmailConfirmed,
                new CustomId(new Guid(user.Id))
            );
            return updatedUser;
        }
    }
}

Library/Library/Controllers/UserBooksController.cs
using Library.AuthenticationService;
using Library.BookService.Domain.Models;
using Library.DB;
using Library.DTOs;
using Library.UserBookService.Domain;
using System.Data.Entity;
using Library.UserService.Domain.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Library.Controllers
{
    public class UserBooksController : Controller
    {
        protected ApplicationDbContext context;
        public UserBooksController()
        {
            context = new ApplicationDbContext();
        }

        public ActionResult Index(string bookId = null)
        {
            if (AuthenticationManager.LoggedUser == null)
                return RedirectToAction("Login", "Home");

            List<UserBook> userBooks = context.UserBooks.Where(b => b.UserId == AuthenticationManager.LoggedUser.Id).ToList();
            UserEntry entry = new UserEntry(AuthenticationManager.LoggedUser.Id);

            if (bookId == null || context.Books.Where(b => b.Id == bookId).FirstOrDefault() == null)
            {
                SetBooksToUser(entry);
                return View(entry.BooksRead);
            }

            Book book = context.Books.Where(b => b.Id == bookId).FirstOrDefault();

            if (userBooks.Where(b => b.BookId == bookId).FirstOrDefault() == null)
            {
                UserBook userBook = new UserBook(bookId, AuthenticationManager.LoggedUser.Id);
                context.UserBooks.Add(userBook);
                book.TimesRead++;
                context.SaveChanges();
                SetBooksToUser(entry);
            }
            else
            {
                UserBook userBook = context.UserBooks.Where(b => b.BookId == bookId && b.UserId == AuthenticationManager.LoggedUser.Id).FirstOrDefault();
                context.UserBooks.Remove(userBook);
                book.TimesRead--;
                context.SaveChanges();
                SetBooksToUser(entry);
            }

            return View(entry.BooksRead);
        }

        private void SetBooksToUser(UserEntry entry)
        {
            List<UserBook> books = context.UserBooks.Where(b => b.UserId == AuthenticationManager.LoggedUser.Id).ToList();

            entry.BooksRead.Clear();
            foreach (var book in books)
            {
                entry.BooksRead.Add(context.Books.Include(b => b.Author).Where(b => b.Id == book.BookId).FirstOrDefault());
            }
        }
    }
}

Library/Library/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("Books", "Index", "Books")</li>
                        @if (Library.AuthenticationService.AuthenticationManager.LoggedUser != null && Library.AuthenticationService.AuthenticationManager.IsAdmin())
                        {
                            <li>@Html.ActionLink("Genres", "Index", "Genres")</li>
                            <li>@Html.ActionLink("Authors", "Index", "Authors")</li>

                        }

                        @if (Library.AuthenticationService.AuthenticationManager.LoggedUser != null)
                        {
                            if (Library.AuthenticationService.AuthenticationManager.IsAdmin())
                            {
                                <li>@Html.ActionLink("Users", "Index", "Admin")</li>
                                <li>@Html.ActionLink("All Exceptions", "AllExceptions", "Admin")</li>

                            }
                            else
                            {
                                <li>@Html.ActionLink("My Books", "Index", "UserBooks")</li>

                            }

                        }
                    </ul>
                    @if (Library.AuthenticationService.AuthenticationManager.LoggedUser != null)
                    {
                        <ul class="nav navbar-nav navbar-right">
                            <li>@Html.ActionLink("Logout", "Logout", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
                        </ul>
                    }
                    else
                    {
                        <ul class="nav navbar-nav navbar-right">
                            <li>@Html.ActionLink("Register", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
                            <li>@Html.ActionLink("Log in", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })</li>
                        </ul>

                    }
                </div>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>